<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kurir_model extends CI_Model
{

    public $table = 'kurir';
    public $id = 'id_kurir';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kurir', $q);
        $this->db->or_like('nis_kurir', $q);
        $this->db->or_like('nama_kurir', $q);
        $this->db->or_like('no_hp_kurir', $q);
        $this->db->or_like('email_kurir', $q);
        $this->db->or_like('foto_kurir', $q);
        $this->db->or_like('id_qrcode', $q);
        $this->db->or_like('tanggal_pembuatan', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('level', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kurir', $q);
        $this->db->or_like('nis_kurir', $q);
        $this->db->or_like('nama_kurir', $q);
        $this->db->or_like('no_hp_kurir', $q);
        $this->db->or_like('email_kurir', $q);
        $this->db->or_like('foto_kurir', $q);
        $this->db->or_like('id_qrcode', $q);
        $this->db->or_like('tanggal_pembuatan', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('level', $q);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function deleteImage($id) {
        $row = $this->get_by_id($id);
        if ($row->foto != "default.png" or $row->foto != "default.jpg") {
            $filename = explode(".", $row->foto)[0];
            return array_map('unlink', glob(FCPATH."image/kurir/$filename.*"));
        }
    }

    function deleteImageUp($id) {
        $row = $this->get_by_id($id);
        if ($_FILES['foto']['name'] == '') {
        }elseif ($row->foto != "default.png" or $row->foto != "default.jpg") {
            $filename = explode(".", $row->foto)[0];
            return array_map('unlink', glob(FCPATH."image/kurir/$filename.*"));
        }
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->deleteImageUp($id);
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->deleteImage($id);
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_model.php */
/* Location: ./application/models/Admin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-21 17:52:52 */
/* http://harviacode.com */