<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Siswa_model extends CI_Model
{

    public $table = 'user';
    public $id = 'id_siswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_siswa', $q);
	$this->db->or_like('nis', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
    $this->db->or_like('no_hp', $q);
	$this->db->or_like('email', $q);
    $this->db->or_like('kelas', $q);
    $this->db->or_like('foto', $q);
    $this->db->or_like('jurusan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id);
        $this->db->like('id_siswa', $q);
	$this->db->or_like('nis', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
    $this->db->or_like('no_hp', $q);
	$this->db->or_like('email', $q);
    $this->db->or_like('kelas', $q);
    $this->db->or_like('foto', $q);
    $this->db->or_like('jurusan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function deleteImage($id) {
        $row = $this->get_by_id($id);
        if ($row->foto != "default.png" or $row->foto != "default.jpg") {
            $filename = explode(".", $row->foto)[0];
            return array_map('unlink', glob(FCPATH."image/siswa/$filename.*"));
        }
    }

    function deleteImageUp($id) {
        $row = $this->get_by_id($id);
        if ($_FILES['foto']['name'] == '') {
        }elseif ($row->foto != "default.png" or $row->foto != "default.jpg") {
            $filename = explode(".", $row->foto)[0];
            return array_map('unlink', glob(FCPATH."image/siswa/$filename.*"));
        }
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->deleteImageUp($id);
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }


    // delete data
    function delete($id)
    {
        $this->deleteImage($id);
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Siswa_model.php */
/* Location: ./application/models/Siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-14 09:54:00 */
/* http://harviacode.com */